apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-api
  namespace: devops-demo
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: devops-demo-api

  template:
    metadata:
      labels:
        app: devops-demo-api
    spec:
      containers:
        - name: devops-demo-api
          image: devops-demo:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 20
          livenessProbe:
            httpGet: 
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
